# Count number of vowels in string
def count_vowels(s):
    count = 0
    for c in s:
        if c in 'aeiouAEIOU':
            count += 1
    return count

string1 = "oivehyexvjsuwlzmtselvznfboyqatugoecwvgktxarcjaakxnfnxzsgzyidcdxljrxqmmjfjnvdqtzoztvenoxssnqunetzjiuoszpfgojuzdhjpagdlnwtbzbxwbwrdszevzkxryfpositumgpidvknnzlmlrornriyeniecrmxhapduwgklxdaovnrgvwfxdsmggptsesyjgtbfxcoadqlmgdzgwzvkrdxgfmlefjcqrlbxdefxabmikxxwrqppjnprqndapetmjayfzvpknkbxhjglzpvfqhrphhnqzcgfihbpgfwjzvksodmprrmrxzyagrxoihhijbgjacxhzrtudfhwsrgfmjcxmduynnqcvmgcrnfufqeozgezxbgxjzsfldozgjftuqbtrjwtgbkipuqxaltshlcochggepqeyjzoxocnmlnpanleabtirncrdrnjnnrqyujbucgopgylnuhbbfcohmacapryvnfrwcsoqkagwcltjobifhshpumnznccfnsfejazixiywvmrdvmjtdclggywgehmobdkwyvuxzebbakbxfobauncbkfrzftcgoerqbqcowanzeqrjjzxolayiaxedssexcn"

print("Number of vowels in string1: ", count_vowels(string1))

string2 = "vxuriwbkgvxxamyqoiryxaajvexbfmnridhoovrmtunmogtghagefuoypugedurmfmbmzlloylafrskdicrdnkebjtufdcsbqmktvohaaupskecvkagyizvfhslfeuyvhfwzpgrsdljatqplexqsqvdjtqizzaaanwkjjewnzuieqapqmqmjvuznufzukithigbljxsfhbmatwaimbumomyreogqjmpszpfkujbnaxgecxzfemevsyqckxzmbmgxlmnldislishbnlfpoafwrvlsygkznyjtgiohbzclbhjmfwolwgowregoyzfhlffdoxqbyvpjkhcxulpsdsjkbppraezupwskqvlakybjuunadrwpxknxfiunqrgoplmrwwdptqpvtgielwdkebslrmnyqhawnuidcrbaaeakzezsedcvvssstlmhtmwnvkxvelwhalsgvbgoujjppngyzohzpufyokjrciqrvzxumrfudgkoiixqlcdwdmnvaqqwalgbofamyakekmwvlkjvijiefzlanwrojtdtznasndgksffbaemdxpborzxkmpzragjnsnfaccqyocoaxolrcqpbvxphouaazmqcvyqcodoai"

print("Number of vowels in string2: ", count_vowels(string2))